name: Deploy to Replit

on:
  push:
    branches:
      - main # Kích hoạt workflow khi có commit mới trên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # Lấy mã nguồn từ kho lưu trữ GitHub hiện tại
        uses: actions/checkout@v3

      - name: Configure Git for Replit # Cấu hình Git để có thể đẩy mã nguồn tới Replit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # RẤT QUAN TRỌNG: Thay thế URL dưới đây bằng URL Git CHÍNH XÁC của Repl của bạn.
          # Dựa trên đường dẫn Replit bạn cung cấp: https://replit.com/@22dh114365/thaovy-app
          # URL Git chính xác sẽ là: https://github.com/22dh114365/thaovy-app.git
          # Đảm bảo bạn đã tạo Personal Access Token (PAT) trên GitHub (Bước 1)
          # và thêm nó vào GitHub Secrets với tên REPLIT_GIT_PAT (Bước 2).
          git remote add replit https://oauth2:${{ secrets.REPLIT_API_KEY }}@github.com/22dh114365/thaovy-app.git

      - name: Push to Replit # Đẩy mã nguồn đã checkout lên kho Git của Replit
        run: git push replit main --force # Sử dụng --force để ghi đè lịch sử nếu cần thiết
        # Khi Replit nhận được push này, nó sẽ tự động triển khai các thay đổi.
