name: Deploy to Replit

on:
  push:
    branches:
      - main # Kích hoạt workflow khi có commit mới trên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # Lấy mã nguồn từ kho lưu trữ GitHub hiện tại
        uses: actions/checkout@v3

      - name: Configure Git for Replit # Cấu hình Git để có thể đẩy mã nguồn tới Replit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # Thêm remote Git cho kho lưu trữ Replit của bạn
          # THAY THẾ "YOUR_REPLIT_USERNAME" bằng tên người dùng Replit của bạn
          # VÀ "YOUR_REPL_NAME" bằng tên Repl (dự án) của bạn trên Replit
          # Ví dụ: https://github.com/NguyenVy167/thaovy-app.git
          git remote add replit https://github.com/YOUR_REPLIT_USERNAME/YOUR_REPL_NAME.git
        # Gợi ý: Nếu kho Replit của bạn là riêng tư hoặc yêu cầu xác thực,
        # bạn có thể cần tạo Personal Access Token (PAT) trên GitHub
        # và thêm nó vào GitHub Secrets của kho lưu trữ này (ví dụ: REPLIT_GIT_PAT).
        # Sau đó, cấu hình URL remote như sau (uncomment nếu cần):
        # run: |
        #   git config --global user.name "GitHub Actions"
        #   git config --global user.email "actions@github.com"
        #   git remote add replit https://oauth2:${{ secrets.REPLIT_GIT_PAT }}@github.com/YOUR_REPLIT_USERNAME/YOUR_REPL_NAME.git

      - name: Push to Replit # Đẩy mã nguồn đã checkout lên kho Git của Replit
        run: git push replit main --force # Sử dụng --force để ghi đè lịch sử nếu cần thiết
        # Khi Replit nhận được push này, nó sẽ tự động triển khai các thay đổi.
